version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-web-api
    restart: unless-stopped
    ports:
      - "3050:3050"
    volumes:
      - ./sessions:/app/sessions
      - ./assets:/app/assets
    environment:
      - PORT=3000
      - API_KEY=${API_KEY:-your_api_key_here}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL:-http://localhost:3000/webhook}
      - NODE_ENV=production
      - SESSIONS_PATH=/app/sessions
      - MAX_ATTACHMENT_SIZE=10000000
      - SET_MESSAGES_AS_SEEN=FALSE
      - RECOVER_SESSIONS=TRUE
      - ENABLE_SWAGGER_ENDPOINT=TRUE
      - SWAGGER_USER=${SWAGGER_USER:-admin}
      - SWAGGER_PASSWORD=${SWAGGER_PASSWORD:-change_this_password}
    # Configure healthcheck to verify the service is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 